import Product from '../models/Product';

const products = [
  // CPU
  {
    name: 'AMD Ryzen 3 3200G',
    description: '4 Cores, 4 Threads, 3.6GHz Base, 4.0GHz Boost, Radeon Vega 8 Graphics',
    price: 2990,
    category: 'CPU',
    brand: 'AMD',
    stock: 50,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'AM4',
      cores: '4',
      threads: '4',
      baseClock: '3.6GHz',
      boostClock: '4.0GHz'
    },
    rating: 4.5,
    reviewCount: 10,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'Intel Core i3-10100F',
    description: '4 Cores, 8 Threads, 3.6GHz Base, 4.3GHz Boost',
    price: 2490,
    category: 'CPU',
    brand: 'Intel',
    stock: 50,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'LGA1200',
      cores: '4',
      threads: '8',
      baseClock: '3.6GHz',
      boostClock: '4.3GHz'
    },
    rating: 4.5,
    reviewCount: 10,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'AMD Athlon 3000G',
    description: '2 Cores, 4 Threads, 3.5GHz, Radeon Vega 3 Graphics',
    price: 1890,
    category: 'CPU',
    brand: 'AMD',
    stock: 50,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'AM4',
      cores: '2',
      threads: '4',
      baseClock: '3.5GHz'
    },
    rating: 4.0,
    reviewCount: 5,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'AMD Ryzen 5 3600',
    description: '6 Cores, 12 Threads, 3.6GHz Base, 4.2GHz Boost',
    price: 4990,
    category: 'CPU',
    brand: 'AMD',
    stock: 50,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'AM4',
      cores: '6',
      threads: '12',
      baseClock: '3.6GHz',
      boostClock: '4.2GHz'
    },
    rating: 4.8,
    reviewCount: 150,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'AMD Ryzen 7 5700X',
    description: '8 Cores, 16 Threads, 3.4GHz Base, 4.6GHz Boost',
    price: 7990,
    category: 'CPU',
    brand: 'AMD',
    stock: 40,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'AM4',
      cores: '8',
      threads: '16',
      baseClock: '3.4GHz',
      boostClock: '4.6GHz'
    },
    rating: 4.9,
    reviewCount: 200,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'Intel Core i5-12400F',
    description: '6 Cores, 12 Threads, 2.5GHz Base, 4.4GHz Boost',
    price: 5490,
    category: 'CPU',
    brand: 'Intel',
    stock: 45,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'LGA1700',
      cores: '6',
      threads: '12',
      baseClock: '2.5GHz',
      boostClock: '4.4GHz'
    },
    rating: 4.7,
    reviewCount: 180,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'Intel Core i7-12700F',
    description: '12 Cores, 20 Threads, 2.1GHz Base, 4.9GHz Boost',
    price: 10990,
    category: 'CPU',
    brand: 'Intel',
    stock: 30,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'LGA1700',
      cores: '12',
      threads: '20',
      baseClock: '2.1GHz',
      boostClock: '4.9GHz'
    },
    rating: 4.8,
    reviewCount: 120,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'AMD Ryzen 5 5600G',
    description: '6 Cores, 12 Threads, 3.9GHz Base, 4.4GHz Boost, Radeon Graphics',
    price: 5290,
    category: 'CPU',
    brand: 'AMD',
    stock: 55,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'AM4',
      cores: '6',
      threads: '12',
      baseClock: '3.9GHz',
      boostClock: '4.4GHz'
    },
    rating: 4.6,
    reviewCount: 95,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'Intel Core i5-10400F',
    description: '6 Cores, 12 Threads, 2.9GHz Base, 4.3GHz Boost',
    price: 3990,
    category: 'CPU',
    brand: 'Intel',
    stock: 60,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'LGA1200',
      cores: '6',
      threads: '12',
      baseClock: '2.9GHz',
      boostClock: '4.3GHz'
    },
    rating: 4.5,
    reviewCount: 110,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'AMD Ryzen 9 5900X',
    description: '12 Cores, 24 Threads, 3.7GHz Base, 4.8GHz Boost',
    price: 14990,
    category: 'CPU',
    brand: 'AMD',
    stock: 25,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'AM4',
      cores: '12',
      threads: '24',
      baseClock: '3.7GHz',
      boostClock: '4.8GHz'
    },
    rating: 5.0,
    reviewCount: 250,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'Intel Core i9-12900K',
    description: '16 Cores, 24 Threads, 3.2GHz Base, 5.2GHz Boost',
    price: 18990,
    category: 'CPU',
    brand: 'Intel',
    stock: 20,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'LGA1700',
      cores: '16',
      threads: '24',
      baseClock: '3.2GHz',
      boostClock: '5.2GHz'
    },
    rating: 4.9,
    reviewCount: 180,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },

  // Mainboard
  {
    name: 'ASROCK A320M-DVS R4.0',
    description: 'Socket AM4, Micro-ATX, DDR4',
    price: 1490,
    category: 'Mainboard',
    brand: 'ASROCK',
    stock: 50,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'AM4',
      chipset: 'A320',
      formFactor: 'Micro-ATX',
      memoryType: 'DDR4'
    },
    rating: 4.0,
    reviewCount: 8,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'GIGABYTE H410M H V2',
    description: 'Socket LGA1200, Micro-ATX, DDR4',
    price: 1990,
    category: 'Mainboard',
    brand: 'GIGABYTE',
    stock: 50,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'LGA1200',
      chipset: 'H410',
      formFactor: 'Micro-ATX',
      memoryType: 'DDR4'
    },
    rating: 4.2,
    reviewCount: 12,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'MSI A520M-A PRO',
    description: 'Socket AM4, Micro-ATX, DDR4',
    price: 1850,
    category: 'Mainboard',
    brand: 'MSI',
    stock: 50,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'AM4',
      chipset: 'A520',
      formFactor: 'Micro-ATX',
      memoryType: 'DDR4'
    },
    rating: 4.3,
    reviewCount: 15,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'ASUS ROG STRIX B550-F GAMING DDR4',
    description: 'Socket AM4, ATX, DDR4, PCIe 4.0',
    price: 5990,
    category: 'Mainboard',
    brand: 'ASUS',
    stock: 40,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'AM4',
      chipset: 'B550',
      formFactor: 'ATX',
      memoryType: 'DDR4'
    },
    rating: 4.8,
    reviewCount: 85,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'MSI MAG B660M MORTAR WIFI DDR4',
    description: 'Socket LGA1700, Micro-ATX, DDR4, WiFi',
    price: 4990,
    category: 'Mainboard',
    brand: 'MSI',
    stock: 45,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'LGA1700',
      chipset: 'B660',
      formFactor: 'Micro-ATX',
      memoryType: 'DDR4'
    },
    rating: 4.7,
    reviewCount: 72,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'GIGABYTE B660M DS3H DDR4',
    description: 'Socket LGA1700, Micro-ATX, DDR4',
    price: 3490,
    category: 'Mainboard',
    brand: 'GIGABYTE',
    stock: 50,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'LGA1700',
      chipset: 'B660',
      formFactor: 'Micro-ATX',
      memoryType: 'DDR4'
    },
    rating: 4.5,
    reviewCount: 60,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'ASROCK B550M STEEL LEGEND DDR4',
    description: 'Socket AM4, Micro-ATX, DDR4, PCIe 4.0',
    price: 3990,
    category: 'Mainboard',
    brand: 'ASROCK',
    stock: 48,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'AM4',
      chipset: 'B550',
      formFactor: 'Micro-ATX',
      memoryType: 'DDR4'
    },
    rating: 4.6,
    reviewCount: 55,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'ASUS TUF GAMING Z690-PLUS WIFI D4',
    description: 'Socket LGA1700, ATX, DDR4, WiFi 6',
    price: 7990,
    category: 'Mainboard',
    brand: 'ASUS',
    stock: 35,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'LGA1700',
      chipset: 'Z690',
      formFactor: 'ATX',
      memoryType: 'DDR4'
    },
    rating: 4.8,
    reviewCount: 95,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'MSI B450M PRO-VDH MAX DDR4',
    description: 'Socket AM4, Micro-ATX, DDR4',
    price: 2290,
    category: 'Mainboard',
    brand: 'MSI',
    stock: 55,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'AM4',
      chipset: 'B450',
      formFactor: 'Micro-ATX',
      memoryType: 'DDR4'
    },
    rating: 4.4,
    reviewCount: 48,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'GIGABYTE Z690 AORUS ELITE AX DDR4',
    description: 'Socket LGA1700, ATX, DDR4, WiFi 6E',
    price: 8990,
    category: 'Mainboard',
    brand: 'GIGABYTE',
    stock: 30,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'LGA1700',
      chipset: 'Z690',
      formFactor: 'ATX',
      memoryType: 'DDR4'
    },
    rating: 4.7,
    reviewCount: 78,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'ASROCK X570 STEEL LEGEND DDR4',
    description: 'Socket AM4, ATX, DDR4, PCIe 4.0',
    price: 6490,
    category: 'Mainboard',
    brand: 'ASROCK',
    stock: 38,
    images: ['/placeholder.jpg'],
    specifications: {
      socket: 'AM4',
      chipset: 'X570',
      formFactor: 'ATX',
      memoryType: 'DDR4'
    },
    rating: 4.6,
    reviewCount: 62,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },

  // VGA
  {
    name: 'GT 1030 2GB GDDR5',
    description: 'NVIDIA GeForce GT 1030, 2GB GDDR5',
    price: 2890,
    category: 'VGA',
    brand: 'GIGABYTE',
    stock: 30,
    images: ['/placeholder.jpg'],
    rating: 4.0,
    reviewCount: 20,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'RX 550 4GB GDDR5',
    description: 'AMD Radeon RX 550, 4GB GDDR5',
    price: 3290,
    category: 'VGA',
    brand: 'POWERCOLOR',
    stock: 30,
    images: ['/placeholder.jpg'],
    rating: 4.1,
    reviewCount: 18,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'GT 730 2GB DDR3',
    description: 'NVIDIA GeForce GT 730, 2GB DDR3',
    price: 1990,
    category: 'VGA',
    brand: 'ASUS',
    stock: 30,
    images: ['/placeholder.jpg'],
    rating: 3.5,
    reviewCount: 10,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'RTX 3060 12GB GDDR6',
    description: 'NVIDIA GeForce RTX 3060, 12GB GDDR6',
    price: 12990,
    category: 'VGA',
    brand: 'ASUS',
    stock: 25,
    images: ['/placeholder.jpg'],
    rating: 4.8,
    reviewCount: 150,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'RTX 4060 Ti 8GB GDDR6',
    description: 'NVIDIA GeForce RTX 4060 Ti, 8GB GDDR6',
    price: 16990,
    category: 'VGA',
    brand: 'MSI',
    stock: 20,
    images: ['/placeholder.jpg'],
    rating: 4.9,
    reviewCount: 85,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'RX 6600 8GB GDDR6',
    description: 'AMD Radeon RX 6600, 8GB GDDR6',
    price: 8990,
    category: 'VGA',
    brand: 'GIGABYTE',
    stock: 30,
    images: ['/placeholder.jpg'],
    rating: 4.6,
    reviewCount: 95,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'RTX 3070 8GB GDDR6',
    description: 'NVIDIA GeForce RTX 3070, 8GB GDDR6',
    price: 18990,
    category: 'VGA',
    brand: 'GIGABYTE',
    stock: 18,
    images: ['/placeholder.jpg'],
    rating: 4.9,
    reviewCount: 200,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'RX 7600 8GB GDDR6',
    description: 'AMD Radeon RX 7600, 8GB GDDR6',
    price: 10990,
    category: 'VGA',
    brand: 'ASROCK',
    stock: 28,
    images: ['/placeholder.jpg'],
    rating: 4.7,
    reviewCount: 72,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'GTX 1650 4GB GDDR6',
    description: 'NVIDIA GeForce GTX 1650, 4GB GDDR6',
    price: 5990,
    category: 'VGA',
    brand: 'MSI',
    stock: 35,
    images: ['/placeholder.jpg'],
    rating: 4.5,
    reviewCount: 110,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'RTX 4070 12GB GDDR6X',
    description: 'NVIDIA GeForce RTX 4070, 12GB GDDR6X',
    price: 22990,
    category: 'VGA',
    brand: 'ASUS',
    stock: 15,
    images: ['/placeholder.jpg'],
    rating: 5.0,
    reviewCount: 125,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'RX 6700 XT 12GB GDDR6',
    description: 'AMD Radeon RX 6700 XT, 12GB GDDR6',
    price: 14990,
    category: 'VGA',
    brand: 'POWERCOLOR',
    stock: 22,
    images: ['/placeholder.jpg'],
    rating: 4.7,
    reviewCount: 88,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'GTX 1660 SUPER 6GB GDDR6',
    description: 'NVIDIA GeForce GTX 1660 SUPER, 6GB GDDR6',
    price: 7990,
    category: 'VGA',
    brand: 'GIGABYTE',
    stock: 32,
    images: ['/placeholder.jpg'],
    rating: 4.6,
    reviewCount: 145,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },

  // Memory
  {
    name: 'KINGSTON FURY BEAST 8GB DDR4 3200MHz',
    description: '8GB (1x8GB) DDR4 3200MHz',
    price: 890,
    category: 'Memory',
    brand: 'KINGSTON',
    stock: 100,
    images: ['/placeholder.jpg'],
    rating: 4.8,
    reviewCount: 50,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'BLACKBERRY MAXIMUS 8GB DDR4 2666MHz',
    description: '8GB (1x8GB) DDR4 2666MHz',
    price: 690,
    category: 'Memory',
    brand: 'BLACKBERRY',
    stock: 100,
    images: ['/placeholder.jpg'],
    rating: 4.0,
    reviewCount: 20,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'CORSAIR VENGEANCE LPX 8GB DDR4 3200MHz',
    description: '8GB (1x8GB) DDR4 3200MHz',
    price: 990,
    category: 'Memory',
    brand: 'CORSAIR',
    stock: 100,
    images: ['/placeholder.jpg'],
    rating: 4.7,
    reviewCount: 40,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'G.SKILL RIPJAWS V 16GB (2x8GB) DDR4 3600MHz',
    description: '16GB (2x8GB) DDR4 3600MHz',
    price: 2190,
    category: 'Memory',
    brand: 'G.SKILL',
    stock: 80,
    images: ['/placeholder.jpg'],
    rating: 4.9,
    reviewCount: 120,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'CORSAIR VENGEANCE RGB PRO 16GB (2x8GB) DDR4 3200MHz',
    description: '16GB (2x8GB) DDR4 3200MHz RGB',
    price: 2490,
    category: 'Memory',
    brand: 'CORSAIR',
    stock: 75,
    images: ['/placeholder.jpg'],
    rating: 4.8,
    reviewCount: 95,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'KINGSTON FURY BEAST RGB 16GB (2x8GB) DDR4 3600MHz',
    description: '16GB (2x8GB) DDR4 3600MHz RGB',
    price: 2290,
    category: 'Memory',
    brand: 'KINGSTON',
    stock: 85,
    images: ['/placeholder.jpg'],
    rating: 4.7,
    reviewCount: 88,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'CORSAIR VENGEANCE DDR5 32GB (2x16GB) 5600MHz',
    description: '32GB (2x16GB) DDR5 5600MHz',
    price: 4990,
    category: 'Memory',
    brand: 'CORSAIR',
    stock: 50,
    images: ['/placeholder.jpg'],
    rating: 4.9,
    reviewCount: 65,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'G.SKILL TRIDENT Z5 RGB 32GB (2x16GB) DDR5 6000MHz',
    description: '32GB (2x16GB) DDR5 6000MHz RGB',
    price: 5990,
    category: 'Memory',
    brand: 'G.SKILL',
    stock: 45,
    images: ['/placeholder.jpg'],
    rating: 5.0,
    reviewCount: 72,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'KINGSTON FURY BEAST 32GB (2x16GB) DDR4 3200MHz',
    description: '32GB (2x16GB) DDR4 3200MHz',
    price: 3490,
    category: 'Memory',
    brand: 'KINGSTON',
    stock: 60,
    images: ['/placeholder.jpg'],
    rating: 4.8,
    reviewCount: 78,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'CORSAIR DOMINATOR PLATINUM RGB 32GB (2x16GB) DDR5 5600MHz',
    description: '32GB (2x16GB) DDR5 5600MHz RGB',
    price: 6990,
    category: 'Memory',
    brand: 'CORSAIR',
    stock: 35,
    images: ['/placeholder.jpg'],
    rating: 5.0,
    reviewCount: 55,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'G.SKILL RIPJAWS V 32GB (2x16GB) DDR4 3600MHz',
    description: '32GB (2x16GB) DDR4 3600MHz',
    price: 3790,
    category: 'Memory',
    brand: 'G.SKILL',
    stock: 55,
    images: ['/placeholder.jpg'],
    rating: 4.8,
    reviewCount: 92,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },

  // Harddisk
  {
    name: 'WD BLUE 1TB',
    description: '1TB HDD 7200RPM SATA3',
    price: 1290,
    category: 'Harddisk',
    brand: 'WD',
    stock: 50,
    images: ['/placeholder.jpg'],
    rating: 4.6,
    reviewCount: 100,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'SEAGATE BARRACUDA 1TB',
    description: '1TB HDD 7200RPM SATA3',
    price: 1250,
    category: 'Harddisk',
    brand: 'SEAGATE',
    stock: 50,
    images: ['/placeholder.jpg'],
    rating: 4.5,
    reviewCount: 90,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'TOSHIBA P300 1TB',
    description: '1TB HDD 7200RPM SATA3',
    price: 1190,
    category: 'Harddisk',
    brand: 'TOSHIBA',
    stock: 50,
    images: ['/placeholder.jpg'],
    rating: 4.3,
    reviewCount: 30,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'WD BLACK 2TB',
    description: '2TB HDD 7200RPM SATA3 High Performance',
    price: 2790,
    category: 'Harddisk',
    brand: 'WD',
    stock: 40,
    images: ['/placeholder.jpg'],
    rating: 4.8,
    reviewCount: 85,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'SEAGATE IRONWOLF 4TB NAS',
    description: '4TB HDD 5900RPM SATA3 NAS',
    price: 4290,
    category: 'Harddisk',
    brand: 'SEAGATE',
    stock: 35,
    images: ['/placeholder.jpg'],
    rating: 4.7,
    reviewCount: 65,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'WD BLUE 2TB',
    description: '2TB HDD 5400RPM SATA3',
    price: 1990,
    category: 'Harddisk',
    brand: 'WD',
    stock: 55,
    images: ['/placeholder.jpg'],
    rating: 4.5,
    reviewCount: 95,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'SEAGATE BARRACUDA 2TB',
    description: '2TB HDD 7200RPM SATA3',
    price: 2090,
    category: 'Harddisk',
    brand: 'SEAGATE',
    stock: 50,
    images: ['/placeholder.jpg'],
    rating: 4.6,
    reviewCount: 88,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'TOSHIBA X300 4TB',
    description: '4TB HDD 7200RPM SATA3 High Performance',
    price: 3990,
    category: 'Harddisk',
    brand: 'TOSHIBA',
    stock: 38,
    images: ['/placeholder.jpg'],
    rating: 4.7,
    reviewCount: 62,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'WD PURPLE 2TB Surveillance',
    description: '2TB HDD 5400RPM SATA3 Surveillance',
    price: 2490,
    category: 'Harddisk',
    brand: 'WD',
    stock: 45,
    images: ['/placeholder.jpg'],
    rating: 4.6,
    reviewCount: 72,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'SEAGATE SKYHAWK 4TB Surveillance',
    description: '4TB HDD 5900RPM SATA3 Surveillance',
    price: 4490,
    category: 'Harddisk',
    brand: 'SEAGATE',
    stock: 32,
    images: ['/placeholder.jpg'],
    rating: 4.8,
    reviewCount: 58,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'TOSHIBA N300 6TB NAS',
    description: '6TB HDD 7200RPM SATA3 NAS',
    price: 5990,
    category: 'Harddisk',
    brand: 'TOSHIBA',
    stock: 28,
    images: ['/placeholder.jpg'],
    rating: 4.7,
    reviewCount: 48,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },

  // SSD
  {
    name: 'HIKVISION C100 240GB',
    description: '240GB SSD SATA3',
    price: 590,
    category: 'SSD',
    brand: 'HIKVISION',
    stock: 100,
    images: ['/placeholder.jpg'],
    rating: 4.2,
    reviewCount: 40,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'WD GREEN 240GB',
    description: '240GB SSD SATA3',
    price: 790,
    category: 'SSD',
    brand: 'WD',
    stock: 100,
    images: ['/placeholder.jpg'],
    rating: 4.5,
    reviewCount: 60,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'KINGSTON A400 240GB',
    description: '240GB SSD SATA3',
    price: 850,
    category: 'SSD',
    brand: 'KINGSTON',
    stock: 100,
    images: ['/placeholder.jpg'],
    rating: 4.6,
    reviewCount: 80,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'SAMSUNG 970 EVO PLUS 500GB NVMe',
    description: '500GB NVMe M.2 PCIe Gen 3.0 x4',
    price: 2290,
    category: 'SSD',
    brand: 'SAMSUNG',
    stock: 70,
    images: ['/placeholder.jpg'],
    rating: 4.9,
    reviewCount: 150,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'WD BLACK SN850X 1TB NVMe',
    description: '1TB NVMe M.2 PCIe Gen 4.0 x4',
    price: 3990,
    category: 'SSD',
    brand: 'WD',
    stock: 60,
    images: ['/placeholder.jpg'],
    rating: 5.0,
    reviewCount: 120,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'KINGSTON NV2 500GB NVMe',
    description: '500GB NVMe M.2 PCIe Gen 4.0 x4',
    price: 1490,
    category: 'SSD',
    brand: 'KINGSTON',
    stock: 85,
    images: ['/placeholder.jpg'],
    rating: 4.5,
    reviewCount: 95,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'SAMSUNG 980 PRO 2TB NVMe',
    description: '2TB NVMe M.2 PCIe Gen 4.0 x4',
    price: 6990,
    category: 'SSD',
    brand: 'SAMSUNG',
    stock: 45,
    images: ['/placeholder.jpg'],
    rating: 5.0,
    reviewCount: 180,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'CRUCIAL P3 PLUS 1TB NVMe',
    description: '1TB NVMe M.2 PCIe Gen 4.0 x4',
    price: 2490,
    category: 'SSD',
    brand: 'CRUCIAL',
    stock: 75,
    images: ['/placeholder.jpg'],
    rating: 4.7,
    reviewCount: 88,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'WD BLUE SN570 1TB NVMe',
    description: '1TB NVMe M.2 PCIe Gen 3.0 x4',
    price: 2190,
    category: 'SSD',
    brand: 'WD',
    stock: 80,
    images: ['/placeholder.jpg'],
    rating: 4.6,
    reviewCount: 102,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'SAMSUNG 990 PRO 1TB NVMe',
    description: '1TB NVMe M.2 PCIe Gen 4.0 x4 7450MB/s',
    price: 4490,
    category: 'SSD',
    brand: 'SAMSUNG',
    stock: 55,
    images: ['/placeholder.jpg'],
    rating: 5.0,
    reviewCount: 135,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'KINGSTON KC3000 2TB NVMe',
    description: '2TB NVMe M.2 PCIe Gen 4.0 x4',
    price: 5990,
    category: 'SSD',
    brand: 'KINGSTON',
    stock: 48,
    images: ['/placeholder.jpg'],
    rating: 4.8,
    reviewCount: 92,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },

  // Power Supply
  {
    name: 'AEROCOOL SUPERB 600W',
    description: '600W Power Supply',
    price: 790,
    category: 'Power Supply',
    brand: 'AEROCOOL',
    stock: 50,
    images: ['/placeholder.jpg'],
    rating: 4.0,
    reviewCount: 30,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'ANTEC ATOM V550',
    description: '550W Power Supply',
    price: 990,
    category: 'Power Supply',
    brand: 'ANTEC',
    stock: 50,
    images: ['/placeholder.jpg'],
    rating: 4.3,
    reviewCount: 40,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'DTECH PW006 450W',
    description: '450W Power Supply',
    price: 450,
    category: 'Power Supply',
    brand: 'DTECH',
    stock: 50,
    images: ['/placeholder.jpg'],
    rating: 3.5,
    reviewCount: 10,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'CORSAIR RM750X 750W 80+ GOLD',
    description: '750W Modular 80+ GOLD',
    price: 3990,
    category: 'Power Supply',
    brand: 'CORSAIR',
    stock: 45,
    images: ['/placeholder.jpg'],
    rating: 4.9,
    reviewCount: 125,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'COOLER MASTER MWE 650W 80+ BRONZE',
    description: '650W 80+ BRONZE',
    price: 1890,
    category: 'Power Supply',
    brand: 'COOLER MASTER',
    stock: 60,
    images: ['/placeholder.jpg'],
    rating: 4.5,
    reviewCount: 88,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'ASUS TUF GAMING 850W 80+ GOLD',
    description: '850W Modular 80+ GOLD',
    price: 4490,
    category: 'Power Supply',
    brand: 'ASUS',
    stock: 38,
    images: ['/placeholder.jpg'],
    rating: 4.8,
    reviewCount: 95,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'GIGABYTE P750GM 750W 80+ GOLD',
    description: '750W Modular 80+ GOLD',
    price: 3290,
    category: 'Power Supply',
    brand: 'GIGABYTE',
    stock: 48,
    images: ['/placeholder.jpg'],
    rating: 4.6,
    reviewCount: 72,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'MSI MAG A650BN 650W 80+ BRONZE',
    description: '650W 80+ BRONZE',
    price: 1690,
    category: 'Power Supply',
    brand: 'MSI',
    stock: 55,
    images: ['/placeholder.jpg'],
    rating: 4.4,
    reviewCount: 65,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'CORSAIR HX1000i 1000W 80+ PLATINUM',
    description: '1000W Modular 80+ PLATINUM Digital',
    price: 6990,
    category: 'Power Supply',
    brand: 'CORSAIR',
    stock: 28,
    images: ['/placeholder.jpg'],
    rating: 5.0,
    reviewCount: 110,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'THERMALTAKE TOUGHPOWER GF1 850W 80+ GOLD',
    description: '850W Modular 80+ GOLD',
    price: 4290,
    category: 'Power Supply',
    brand: 'THERMALTAKE',
    stock: 42,
    images: ['/placeholder.jpg'],
    rating: 4.7,
    reviewCount: 82,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'SEASONIC FOCUS GX-750 750W 80+ GOLD',
    description: '750W Modular 80+ GOLD',
    price: 3790,
    category: 'Power Supply',
    brand: 'SEASONIC',
    stock: 35,
    images: ['/placeholder.jpg'],
    rating: 4.9,
    reviewCount: 105,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },

  // Case
  {
    name: 'CUBIC ARMOR',
    description: 'ATX Case, Tempered Glass',
    price: 990,
    category: 'Case',
    brand: 'CUBIC',
    stock: 30,
    images: ['/placeholder.jpg'],
    rating: 4.0,
    reviewCount: 20,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'TSUNAMI E-SPORT D7',
    description: 'ATX Case, RGB Fan',
    price: 1190,
    category: 'Case',
    brand: 'TSUNAMI',
    stock: 30,
    images: ['/placeholder.jpg'],
    rating: 4.2,
    reviewCount: 25,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'AEROCOOL CS-1101',
    description: 'ATX Case, Basic',
    price: 790,
    category: 'Case',
    brand: 'AEROCOOL',
    stock: 30,
    images: ['/placeholder.jpg'],
    rating: 3.8,
    reviewCount: 15,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'NZXT H510 ELITE',
    description: 'ATX Mid Tower, Tempered Glass, RGB',
    price: 4990,
    category: 'Case',
    brand: 'NZXT',
    stock: 35,
    images: ['/placeholder.jpg'],
    rating: 4.8,
    reviewCount: 145,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'CORSAIR 4000D AIRFLOW',
    description: 'ATX Mid Tower, Tempered Glass, High Airflow',
    price: 3490,
    category: 'Case',
    brand: 'CORSAIR',
    stock: 42,
    images: ['/placeholder.jpg'],
    rating: 4.9,
    reviewCount: 168,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'LIAN LI O11 DYNAMIC',
    description: 'ATX Mid Tower, Dual Tempered Glass',
    price: 4490,
    category: 'Case',
    brand: 'LIAN LI',
    stock: 28,
    images: ['/placeholder.jpg'],
    rating: 5.0,
    reviewCount: 195,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'COOLER MASTER MASTERBOX TD500 MESH',
    description: 'ATX Mid Tower, Mesh Front, RGB',
    price: 2990,
    category: 'Case',
    brand: 'COOLER MASTER',
    stock: 48,
    images: ['/placeholder.jpg'],
    rating: 4.7,
    reviewCount: 122,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'FRACTAL DESIGN MESHIFY C',
    description: 'ATX Mid Tower, Mesh Front, Tempered Glass',
    price: 3290,
    category: 'Case',
    brand: 'FRACTAL DESIGN',
    stock: 38,
    images: ['/placeholder.jpg'],
    rating: 4.8,
    reviewCount: 135,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'ASUS TUF GAMING GT501',
    description: 'ATX Mid Tower, Tempered Glass, RGB',
    price: 3990,
    category: 'Case',
    brand: 'ASUS',
    stock: 32,
    images: ['/placeholder.jpg'],
    rating: 4.6,
    reviewCount: 88,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'DEEPCOOL MATREXX 55 MESH',
    description: 'ATX Mid Tower, Mesh Front, Tempered Glass, RGB',
    price: 1990,
    category: 'Case',
    brand: 'DEEPCOOL',
    stock: 55,
    images: ['/placeholder.jpg'],
    rating: 4.5,
    reviewCount: 102,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'PHANTEKS ECLIPSE P500A',
    description: 'ATX Mid Tower, Mesh Front, Tempered Glass, RGB',
    price: 4790,
    category: 'Case',
    brand: 'PHANTEKS',
    stock: 25,
    images: ['/placeholder.jpg'],
    rating: 4.9,
    reviewCount: 158,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },

  // CPU Cooler
  {
    name: 'TSUNAMI TSS-1000',
    description: 'RGB CPU Cooler',
    price: 290,
    category: 'CPU Cooler',
    brand: 'TSUNAMI',
    stock: 50,
    images: ['/placeholder.jpg'],
    rating: 4.0,
    reviewCount: 20,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'ID-COOLING SE-214-XT',
    description: 'CPU Air Cooler, 120mm Fan',
    price: 690,
    category: 'CPU Cooler',
    brand: 'ID-COOLING',
    stock: 50,
    images: ['/placeholder.jpg'],
    rating: 4.5,
    reviewCount: 40,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'COOLER MASTER I71C',
    description: 'RGB CPU Cooler for Intel',
    price: 390,
    category: 'CPU Cooler',
    brand: 'COOLER MASTER',
    stock: 50,
    images: ['/placeholder.jpg'],
    rating: 4.2,
    reviewCount: 30,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'NZXT KRAKEN X63 280mm AIO',
    description: '280mm RGB AIO Liquid Cooler',
    price: 5990,
    category: 'CPU Cooler',
    brand: 'NZXT',
    stock: 35,
    images: ['/placeholder.jpg'],
    rating: 4.9,
    reviewCount: 145,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'CORSAIR iCUE H150i ELITE 360mm AIO',
    description: '360mm RGB AIO Liquid Cooler',
    price: 6990,
    category: 'CPU Cooler',
    brand: 'CORSAIR',
    stock: 30,
    images: ['/placeholder.jpg'],
    rating: 5.0,
    reviewCount: 168,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'DEEPCOOL AK620',
    description: 'Dual Tower Air Cooler, 2x120mm Fans',
    price: 1990,
    category: 'CPU Cooler',
    brand: 'DEEPCOOL',
    stock: 55,
    images: ['/placeholder.jpg'],
    rating: 4.8,
    reviewCount: 125,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'BE QUIET! DARK ROCK PRO 4',
    description: 'Premium Air Cooler, Dual Tower',
    price: 3490,
    category: 'CPU Cooler',
    brand: 'BE QUIET',
    stock: 42,
    images: ['/placeholder.jpg'],
    rating: 4.9,
    reviewCount: 152,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'ARCTIC LIQUID FREEZER II 240mm',
    description: '240mm AIO Liquid Cooler',
    price: 3290,
    category: 'CPU Cooler',
    brand: 'ARCTIC',
    stock: 48,
    images: ['/placeholder.jpg'],
    rating: 4.8,
    reviewCount: 138,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'ASUS ROG RYUJIN II 360mm AIO',
    description: '360mm RGB AIO with LiveDash OLED',
    price: 9990,
    category: 'CPU Cooler',
    brand: 'ASUS',
    stock: 22,
    images: ['/placeholder.jpg'],
    rating: 5.0,
    reviewCount: 95,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: true,
    isFlashSale: false
  },
  {
    name: 'COOLER MASTER HYPER 212 RGB',
    description: 'Tower Air Cooler with RGB Fan',
    price: 1290,
    category: 'CPU Cooler',
    brand: 'COOLER MASTER',
    stock: 65,
    images: ['/placeholder.jpg'],
    rating: 4.6,
    reviewCount: 185,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'LIAN LI GALAHAD AIO 240mm',
    description: '240mm RGB AIO Liquid Cooler',
    price: 3990,
    category: 'CPU Cooler',
    brand: 'LIAN LI',
    stock: 38,
    images: ['/placeholder.jpg'],
    rating: 4.7,
    reviewCount: 112,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  },
  {
    name: 'THERMALTAKE TOUGHLIQUID 360 ARGB',
    description: '360mm RGB AIO Liquid Cooler',
    price: 4990,
    category: 'CPU Cooler',
    brand: 'THERMALTAKE',
    stock: 32,
    images: ['/placeholder.jpg'],
    rating: 4.6,
    reviewCount: 98,
    isActive: true,
    showInCategory: true,
    sold: 0,
    isFeatured: false,
    isFlashSale: false
  }
];

export const seedProducts = async () => {
  try {
    console.log('🌱 Seeding cheap products...');
    
    for (const product of products) {
      const exists = await Product.findOne({ name: product.name });
      if (!exists) {
        await Product.create(product);
        console.log(`✅ Created: ${product.name}`);
      } else {
        // Update existing product with new specifications
        await Product.findOneAndUpdate(
          { name: product.name },
          product,
          { new: true }
        );
        console.log(`🔄 Updated: ${product.name}`);
      }
    }
    
    console.log('✨ Cheap products seeding completed!');
  } catch (error) {
    console.error('❌ Error in seedProducts:', error);
    throw error;
  }
};
