import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/app/ClientProvider";
import ChatBot from "@/app/component/ChatBot/ChatBot";

const prompt = Prompt({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ["latin", "thai"],
  variable: "--font-prompt",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prompt.variable} antialiased`}
      >
        <ClientProvider>
          {children}
        </ClientProvider>
        <ChatBot />
      </body>
    </html>
  );
}
